name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build c++
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j `nproc`
